#服务端口
server:
   port: 8204
   compression:
      enable: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain
      #min-response-size: 

# 服务应用名
# 配置中心地址
#   快速失败
#   读取服务配置中心的配置文件名称为：{spring.application.name }-{spring.profiles.active }.yml
# spring cloud 与 cloud整合配置
# sprng boot 与 kafka 整合配置
spring:
   cloud:
      stream:
         kafka:
            binder:
               brokers: localhost:9092,localhost:9093
               defaultBrokerPort: 9092
               zkNodes: localhost:2181
               defaultZkPort: 2181

   kafka:
      bootstrap-servers: localhost:9092,localhost:9093
      producer: 
         retries: 0
         batch-size: 16384
         buffer-memory: 33554432
         key-serializer: org.apache.kafka.common.serialization.StringSerializer
         value-serializer: org.apache.kafka.common.serialization.StringSerializer
      consumer:
         group-id: test-consumer-group
         auto-offset-reset: earliest
         enable-auto-commit: true
         auto-commit-interval: 100
         key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
         value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

# 关闭安全验证
management.security.enabled: false

user:
   name: taotao
   age: 20
   call: 182
