#服务端口
server:
   port: 8004
   compression:
      enable: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain
      #min-response-size: 

# 实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true\
# 此客户端是否获取eureka服务器注册表上的注册信息，默认为true
# eureka:
#    instance:
#       appname: atmm-config-client-demo-server
#       hostname: ${spring.cloud.client.ipAddress}
#       instance-id: ${spring.application.name}-${spring.cloud.client.ipAddress}:${server.port}
#    client:
#       serviceUrl:
#          defaultZone: http://atfmserver:atfmserver@192.168.243.197:8000/eureka/
user:
   name: taotao
   age: 20
   call: 182
